name: Build release packages for libndtp

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  package:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: mac
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      
      - name: Update vcpkg
        run: |
          cd external/microsoft/vcpkg
          ./bootstrap-vcpkg.sh
      
      - name: Build and package
        run: |
          bash ops/package.sh
