name: main

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Build
        run: |
          VCPKG_MANIFEST_FEATURES="tests" make configure
          make build

      - name: Test
        run: |
          make test
